"use client";
import {useState} from "react";
import {Pencil,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Textarea} from "@/components/ui/textarea";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {TASKS} from "@/lib/relay/catalog";
import type {Command,EncounterState,Plan,Proposal,Snapshot,Category} from "@/lib/relay/types";
export function PlanEditor({state,plan,persona,act,disabled}:{state:EncounterState;plan:Plan;persona:string;act:(c:Command)=>Promise<Snapshot>;disabled:boolean}) {
  const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const [draft,setDraft]=useState<Proposal|null>(null);
  const start=()=>{setDraft(structuredClone({summary:plan.summary,concerns:plan.concerns,unknowns:plan.unknowns,conflicts:plan.conflicts,handoff:plan.handoff,tasks:plan.tasks}));setError("");setOpen(true);};
  const save=async()=>{if(!draft)return;setSaving(true);try{await act({action:"edit-plan",actor:persona,planId:plan.id,proposal:draft});setOpen(false);}catch(e){setError(e instanceof Error?e.message:"Could not save review edits.");}finally{setSaving(false);}};
  return <><Button variant="outline" disabled={disabled} onClick={start}><Pencil/> Edit proposal</Button><Dialog open={open} onOpenChange={v=>!saving&&setOpen(v)}><DialogContent className="plan-dialog"><DialogHeader><DialogTitle>Review and edit proposal</DialogTitle><DialogDescription>These edits create a new draft. Staff receive tasks only after approval.</DialogDescription></DialogHeader>{draft?<div className="plan-edit-fields">
    <label className="field-label">Summary<Textarea value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label>
    <div className="input-grid">{Object.entries(draft.handoff).map(([key,value])=><label key={key} className="field-label">{key.charAt(0).toUpperCase()+key.slice(1)}<Textarea value={value} onChange={e=>setDraft({...draft,handoff:{...draft.handoff,[key]:e.target.value}})}/></label>)}</div>
    {(["concerns","unknowns","conflicts"] as const).map(key=><label key={key} className="field-label">{key} · one per line<Textarea value={draft[key].join("\n")} onChange={e=>setDraft({...draft,[key]:e.target.value.split("\n").filter(Boolean)})}/></label>)}
    <h3>Preparation assignments</h3>{draft.tasks.map((task,i)=><div className="edit-task" key={task.category}><div className="panel-heading"><strong>{TASKS[task.category].title}</strong><Button variant="ghost" size="icon" aria-label={"Remove "+TASKS[task.category].title} onClick={()=>setDraft({...draft,tasks:draft.tasks.filter((_,j)=>i!==j)})}><Trash2/></Button></div><div className="input-grid"><Select value={task.personId} onValueChange={value=>setDraft({...draft,tasks:draft.tasks.map((t,j)=>j===i?{...t,personId:value}:t)})}><SelectTrigger aria-label="Assigned staff"><SelectValue/></SelectTrigger><SelectContent>{state.people.filter(p=>p.role===TASKS[task.category].role).map(p=><SelectItem disabled={!p.available} key={p.id} value={p.id}>{p.name}{p.available?"":" · unavailable"}</SelectItem>)}</SelectContent></Select>{TASKS[task.category].room?<Select value={task.roomId||""} onValueChange={value=>setDraft({...draft,tasks:draft.tasks.map((t,j)=>j===i?{...t,roomId:value}:t)})}><SelectTrigger aria-label="Task location"><SelectValue placeholder="Select location"/></SelectTrigger><SelectContent>{state.rooms.filter(r=>r.kind===TASKS[task.category].room).map(r=><SelectItem disabled={r.status==="occupied"} key={r.id} value={r.id}>{r.label} · {r.status}</SelectItem>)}</SelectContent></Select>:null}</div><label className="field-label">Rationale<Textarea value={task.rationale} onChange={e=>setDraft({...draft,tasks:draft.tasks.map((t,j)=>j===i?{...t,rationale:e.target.value}:t)})}/></label></div>)}
    <Select value="" onValueChange={value=>{const category=value as Category,rule=TASKS[category],person=state.people.find(p=>p.role===rule.role&&p.available),room=state.rooms.find(r=>r.kind===rule.room&&r.status!=="occupied");if(!person||(rule.room&&!room)){setError("No available staff or location for this category. Update availability first.");return;}setDraft({...draft,tasks:[...draft.tasks,{category,personId:person.id,roomId:room?.id||null,rationale:"Preparation added by the ER lead after review of the latest field report.",evidenceIds:[state.notes.at(-1)!.id]}]});}}><SelectTrigger aria-label="Add preparation"><SelectValue placeholder="Add a preparation category"/></SelectTrigger><SelectContent>{Object.entries(TASKS).filter(([key])=>!draft.tasks.some(t=>t.category===key)).map(([key,rule])=><SelectItem key={key} value={key}>{rule.title}</SelectItem>)}</SelectContent></Select>
    {error?<p className="inline-error" role="alert">{error}</p>:null}<Button disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save reviewed draft"}</Button>
  </div>:null}</DialogContent></Dialog></>;
}
