"use client";
import {useState} from "react";
import {Check,CheckCheck,ExternalLink,MapPin,ShieldCheck,Users,AlertCircle} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Textarea} from "@/components/ui/textarea";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Switch} from "@/components/ui/switch";
import {TASKS} from "@/lib/relay/catalog";
import type {Assignment,Command,EncounterState,Snapshot} from "@/lib/relay/types";
import {PlanEditor} from "./plan-editor";

export const statusLabel:Record<string,string>={sent:"Awaiting acknowledgment",acknowledged:"Acknowledged",ready:"Ready",blocked:"Blocked",superseded:"Replaced"};
export const statusTone:Record<string,string>={sent:"neutral",acknowledged:"amber",ready:"success",blocked:"danger",superseded:"neutral"};
type Run=(c:Command,message?:string)=>Promise<boolean>;
export function CoordinationPanel({state,persona,isLead,act,run,busy,sessionId}:{state:EncounterState;persona:string;isLead:boolean;act:(c:Command)=>Promise<Snapshot>;run:Run;busy:boolean;sessionId:string}){
const plan=state.plans.at(-1);const stale=plan&&(plan.clinicalRevision!==state.clinicalRevision||plan.resourceRevision!==state.resourceRevision);
const active=state.assignments.filter(a=>a.status!=="superseded");
return <section className="panel coordination-panel"><div className="panel-heading"><h2><ShieldCheck size={18}/> Coordination plan</h2><span className={"pill "+(plan?.approvedAt?"success":"amber")}>{plan?.approvedAt?"Dispatched":"ER lead approval required"}</span></div>
{plan?<><div className="plan-intro"><strong>{plan.tasks.length} proposed preparations</strong><span>{plan.source==="gemini"?"Agent-generated":"Scripted rehearsal"} · {plan.editedBy?"Edited by ER lead":"Ready for review"}</span></div><div className="proposed-tasks">{plan.tasks.map(task=>{const person=state.people.find(p=>p.id===task.personId)!;const room=state.rooms.find(r=>r.id===task.roomId);return <article className="proposed-task" key={task.category}><div className="task-category"><span className="small-avatar">{person.initials}</span><div><h3>{TASKS[task.category].title}</h3><p>{person.name} · {person.label}</p></div></div><span className="task-location"><MapPin size={13}/>{room?.label||"Blood bank"}</span><p className="task-instruction">{TASKS[task.category].instruction}</p><p className="rationale">{task.rationale}</p><div className="evidence">Evidence: {task.evidenceIds.map(id=><a key={id} href={"#evidence-"+id}>{id}</a>)}</div></article>;})}</div>
{stale?<p className="inline-error">New information or resource availability has arrived. Refresh the draft before approval.</p>:null}
{isLead&&!plan.approvedAt?<div className="approval-actions"><PlanEditor state={state} plan={plan} persona={persona} act={act} disabled={busy||!!stale}/><Button disabled={busy||!!stale||plan.tasks.length===0} onClick={()=>void run({action:"approve",actor:persona,planId:plan.id},"Plan approved. Preparation tasks dispatched.")}><CheckCheck/> Approve and dispatch</Button></div>:plan.approvedAt?<div className="info-strip"><Check size={14}/> Approved by Dr. Sofia Reyes at {new Date(plan.approvedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}. {active.filter(t=>t.status==="ready").length} of {active.length} assignments ready.</div>:<div className="info-strip">The ER lead reviews this proposal before the team receives assignments.</div>}
</>:<div className="empty-state"><Users size={30}/><h3>No tasks dispatched</h3><p>Run the agent, then open the ER lead view to review its proposal.</p></div>}
{active.length>0?<div className="readiness"><h3>Receiving team readiness</h3><Table><TableHeader><TableRow><TableHead>Team member</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Staff view</span></TableHead></TableRow></TableHeader><TableBody>{active.map(task=><TableRow key={task.id}><TableCell><strong>{state.people.find(p=>p.id===task.personId)?.name}</strong><span className="table-secondary">{TASKS[task.category].title}</span>{task.statusNote?<span className="blocker-note">{task.statusNote}</span>:null}</TableCell><TableCell><span className={"pill "+statusTone[task.status]}>{statusLabel[task.status]}</span></TableCell><TableCell><a className="external-link" title="Open staff view" href={"/?session="+sessionId+"&persona="+task.personId} target="_blank" rel="noreferrer"><ExternalLink size={16}/><span className="sr-only">Open {state.people.find(p=>p.id===task.personId)?.name} view</span></a></TableCell></TableRow>)}</TableBody></Table></div>:null}
</section>;
}
function StaffTask({task,state,run,busy}:{task:Assignment;state:EncounterState;run:Run;busy:boolean}){
const [note,setNote]=useState("");const [showBlocker,setShowBlocker]=useState(false);
return <article className="panel staff-task"><div className="panel-heading"><h2>{TASKS[task.category].title}</h2><span className={"pill "+statusTone[task.status]}>{statusLabel[task.status]}</span></div><p className="staff-location"><MapPin/>{state.rooms.find(r=>r.id===task.roomId)?.label||"Blood bank"}</p><p className="staff-instruction">{task.instruction}</p><dl className="sbar">{Object.entries(task.brief).map(([label,value])=><div key={label}><dt>{label.charAt(0).toUpperCase()+label.slice(1)}</dt><dd>{value||"Not documented"}</dd></div>)}</dl>
{task.statusNote?<div className="inline-error">Reported blocker: {task.statusNote}</div>:null}
<div className="staff-actions"><Button variant="outline" disabled={busy||task.status==="acknowledged"||task.status==="ready"} onClick={()=>void run({action:"task",actor:task.personId,taskId:task.id,status:"acknowledged",note:""},"Acknowledgment sent to the ER lead.")}><Check/> Acknowledge</Button><Button disabled={busy||task.status==="ready"} onClick={()=>void run({action:"task",actor:task.personId,taskId:task.id,status:"ready",note:""},"Readiness shared with the team.")}><CheckCheck/> Ready</Button><Button variant="ghost" disabled={busy} onClick={()=>setShowBlocker(v=>!v)}><AlertCircle/> Blocked</Button></div>
{showBlocker?<div className="blocker-form"><label className="field-label" htmlFor={"blocker-"+task.id}>What is preventing readiness?</label><Textarea id={"blocker-"+task.id} value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder="For example: equipment unavailable; need an alternate bay."/><Button disabled={busy||!note.trim()} variant="destructive" onClick={()=>void run({action:"task",actor:task.personId,taskId:task.id,status:"blocked",note},"Blocker sent to the ER lead.").then(saved=>{if(saved)setShowBlocker(false);})}>Report blocker</Button></div>:null}
<p className="task-history">{task.history.length} status events · Last update {new Date(task.updatedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</p></article>;
}
export function StaffAssignments({state,persona,run,busy}:{state:EncounterState;persona:string;run:Run;busy:boolean}){const tasks=state.assignments.filter(t=>t.personId===persona&&t.status!=="superseded");return <div className="panel-stack">{tasks.length?tasks.map(task=><StaffTask key={task.id} task={task} state={state} run={run} busy={busy}/>):<section className="panel empty-state"><Users size={30}/><h3>No assignment yet</h3><p>Your preparation responsibilities will appear when the ER lead approves dispatch.</p><span className="pill neutral">Standby</span></section>}</div>;}
export function Resources({state,persona,run,busy}:{state:EncounterState;persona:string;run:Run;busy:boolean}) {return <section className="panel"><div className="panel-heading"><h2><MapPin size={18}/> Rooms &amp; availability</h2><span className="pill neutral">Fictional resources</span></div><div className="resource-list">{state.rooms.map(room=><div key={room.id}><span><strong>{room.label}</strong><small>{room.status}</small></span><Switch aria-label={"Make "+room.label+" available"} checked={room.status!=="occupied"} disabled={busy||room.status==="reserved"} onCheckedChange={available=>void run({action:"resource",actor:persona,kind:"room",id:room.id,available})}/></div>)}</div><h3 className="subheading">Standby staff</h3><div className="resource-list">{state.people.filter(p=>p.role!=="emt"&&p.role!=="lead").map(person=><div key={person.id}><span><strong>{person.name}</strong><small>{person.label} · {person.available?"Available":"Unavailable"}</small></span><Switch aria-label={"Make "+person.name+" available"} checked={person.available} disabled={busy} onCheckedChange={available=>void run({action:"resource",actor:persona,kind:"person",id:person.id,available})}/></div>)}</div></section>;}
